modLoader = "javafml"
loaderVersion = "[4,)"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "logo.png"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
type = "required"
versionRange = "[6.0.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.0,)"
ordering = "NONE"
side = "BOTH"
